version: '3.7'
services:
  db:
    image: mysql
    container_name: mysql_test
    restart: always
    # command: /usr/bin/mysql --initialize-insecure --user=mysql
    environment:
      MYSQL_DATABASE: 'aplication'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysql'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456789'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456789'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
     - "./mysql/:/var/lib/mysql" #local
